// TEMPORARY — old-system PAF → new full URL.
// When all traffic has migrated, delete this file and remove its import + check from route.ts.
export const LEGACY_PAF_REDIRECTS: Record<string, string> = {
  t5cra: "https://healthyrations.com/go/shy85hcf",
  t2v3v: "https://healthyrations.com/go/p7b82s2w",
  twecf: "https://healthyrations.com/go/a2a46mkn",
  ttzp4: "https://healthyrations.com/go/ki5t6rx4",
  trf2p: "https://healthyrations.com/go/fots5jef",
  tn3a9: "https://healthyrations.com/go/32djcz2k",
  thhnu: "https://healthyrations.com/go/npoa5zhf",
  te4ze: "https://healthyrations.com/go/ntx0mmst",
  tcm93: "https://healthyrations.com/go/wwoszf8t",
  s96mn: "https://healthyrations.com/go/pq6lk27d",
  s7pv8: "https://healthyrations.com/go/kqyd889q",
  s478t: "https://healthyrations.com/go/s38gbm3a",
  s2rhd: "https://healthyrations.com/go/67ay3pcw",
  sv9u2: "https://healthyrations.com/go/8gi6e659",
  sts7m: "https://healthyrations.com/go/oz7vo8nu",
  srbf7: "https://healthyrations.com/go/420bnpd4",
  snuts: "https://healthyrations.com/go/7t015h7q",
  shc6c: "https://healthyrations.com/go/7x1ytxdu",
  sewez: "https://healthyrations.com/go/gz2xica1",
  r9z46: "https://healthyrations.com/go/ff5baemp",
  r7gdr: "https://healthyrations.com/go/f2mgsv1s",
  r43rb: "https://healthyrations.com/go/3588kkjc",
  r2h3w: "https://healthyrations.com/go/0pxad8xv",
  rv5cg: "https://healthyrations.com/go/nfu64z3u",
  rnqba: "https://healthyrations.com/go/wcnl03pi",
  rtnp5: "https://healthyrations.com/go/es8w4wce",
  rq62q: "https://healthyrations.com/go/k5af06sq",

}
