name: Trigger Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel BurnSong
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
      - name: Deploy Project Onyx
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_ONYX }}"
      - name: Deploy Project Sdamg
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_SDAMG }}"
      - name: Deploy Project Richmondbalance
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_RCMB }}"
      - name: Deploy Project Discrevolt
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_DSCV }}"
      - name: Deploy Project Silvermoon
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_SLVR }}"
      - name: Deploy Project Sunmasterusa
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_SNMS }}"

        
